# Experiment Configuration
experiment:
  name: "ResNet-Cifar100 Experiment"

# Logging Configuration
logging:
  log_file: "cifar100_experiment.log"
  log_level: "INFO"
  log_dir: "runs/ResNet-Cifar100"  # Directory for TensorBoard logs

# Data Configuration
data:
  dataset_name: "CIFAR100"
  batch_size: 256
  num_workers: 4
  download_path: "./data"
  shuffle: true  # Shuffle training data
  validation_split: 0.1  # Fraction of training data for validation

# Model Configuration
model:
  name: "ResNet101"  # Options: ResNet50, ResNet101, ResNet152
  num_classes: 100
  input_channels: 3

# Optimizer Configuration
optimizer:
  name: "Adam"  # Options: Adam, SGD, etc.
  lr: 0.001
  weight_decay: 0.0001

# Scheduler Configuration
scheduler:
  name: "StepLR"  # Options: StepLR, ReduceLROnPlateau, CosineAnnealingLR, etc.
  step_size: 10  # Applicable for StepLR
  gamma: 0.1      # Applicable for StepLR
  patience: 5     # Applicable for ReduceLROnPlateau
  T_max: 50       # Applicable for CosineAnnealingLR
  min_lr: 1e-5    # Applicable for some schedulers

# Training Configuration
training:
  num_epochs: 50
  gradient_clip_value: 1.0  # Optional: Set to None if not using
  use_scheduler: true       # Whether to use a learning rate scheduler

# Device Configuration
device: "cuda"  # Options: "cuda" or "cpu"
